name: Deploy to Server

on:
  push:
    branches:
      - main  # Или другая ветка, которую вы используете для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Start SSH agent and add key
        run: |
          # Запуск SSH-агента
          eval $(ssh-agent -s)
          
          # Использование expect для добавления ключа с паролем
          expect <<- DONE
          spawn ssh-add /dev/stdin <<< "$SSH_PRIVATE_KEY"
          expect "Enter passphrase"
          send "$SSH_PASSPHRASE\r"
          expect eof
          DONE
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@103.54.58.185 << 'EOF'
            cd /var/www/iris/
            git pull origin main
            # Запуск команд для деплоя (например, перезапуск сервиса, компиляция кода и т.д.)
            npm install
            npm run build
          EOF
